#!/bin/bash

# SOURCE/TARGET 구성
PROSYNC_SOURCE_MODE=TAC
PROSYNC_TARGET_MODE=TSC
PROSYNC_SOURCE_TOP_ID=prosync_sync
PROSYNC_TARGET_TOP_ID=${PROSYNC_SOURCE_TOP_ID}

# SOURCE/TARGET 유저
PROSYNC_SOURCE_USER=prosync
PROSYNC_TARGET_USER=prosync

# SOURCE/TARGET 유저
PROSYNC_SOURCE_USER=prosync
PROSYNC_TARGET_USER=prosync

# SOURCE/TARGET 디비 링크
PROSYNC_SOURCE_DBLINK=p_source
PROSYNC_TARGET_DBLINK=p_target


#####################################################################################
# SOURCE/TARGET 동기화 차이 확인
PROSYNC_SOURCE_TSN=$((RANDOM % 32767)) #랜덤 16비트 정수의 최대 값 32767
PROSYNC_TARGET_TSN=$((RANDOM % 32767)) #랜덤 16비트 정수의 최대 값 32767
PROSYNC_TSN_GAP=$((PROSYNC_SOURCE_TSN - PROSYNC_TARGET_TSN)) #랜덤 16비트 정수의 최대 값 32767

PROSYNC_CURRENT_TIME=`date +%Y/%m/%d" "%T`

PROSYNC_SOURCE_TIME=`date +%Y/%m/%d" "%T`
PROSYNC_TARGET_TIME=`date +%Y/%m/%d" "%T`

PROSYNC_TARGET_TSN=$((RANDOM % 32767)) #랜덤 16비트 정수의 최대 값 32767

PROSYNC_SOURCE_UNIX_TIME=`date +%s`
PROSYNC_TARGET_UNIX_TIME=`date +%s`
PROSYNC_TARGET_UNIX_TIME=$((PROSYNC_TARGET_UNIX_TIME - 1))
PROSYNC_UNIX_TIME_GAP=$((PROSYNC_SOURCE_UNIX_TIME - PROSYNC_TARGET_UNIX_TIME))

ROSYNC_HOURS_TIME_GAP=$((PROSYNC_UNIX_TIME_GAP / 3600))  # 시간
PROSYNC_MINUTES_TIME_GAP=$(((PROSYNC_UNIX_TIME_GAP % 3600) / 60))  # 분
PROSYNC_SECONDS_TIME_GAP=$((PROSYNC_UNIX_TIME_GAP % 60))  # 초


clear
echo ""
printf "############################################################################################################\n"
printf " ProSync GAP TSN Checking\n"
printf "############################################################################################################\n"
printf "  %-30s %-30s %-30s\n" "SOURCE(${PROSYNC_SOURCE_MODE})" "TARGET(${PROSYNC_TARGET_MODE})" "TSN GAP/CURRENT TIME"
printf " %-30s %-30s %-30s\n" "------------------" "------------------" "------------------------------------------"
printf "  %-30s %-30s %-30s\n" "${PROSYNC_SOURCE_USER}" "${PROSYNC_TARGET_USER}" "GAP: ${PROSYNC_TSN_GAP} (CUR: ${PROSYNC_CURRENT_TIME})"
#printf "  %-30s %-30s %-30s\n" "" "" "${PROSYNC_CURRENT_TIME}"
printf "\n"
printf "############################################################################################################\n"
printf " ProSync SOURCE/TARGET TSN Checking\n"
printf "############################################################################################################\n"
printf "   - CURRENT TIME      : %-10s\n" "$PROSYNC_CURRENT_TIME"
printf "   - SOURCE TSN(TIME)  : %-10d         (apply time: %-20s)\n" "$PROSYNC_SOURCE_TSN" "$PROSYNC_SOURCE_TIME"
printf "   - TARGET TSN(TIME)  : %-10d         (apply time: %-20s)\n" "$PROSYNC_TARGET_TSN" "$PROSYNC_TARGET_TIME"
printf "   - SOURCE/TARGET GAP : %-10d         (gap time: %-2d hours, %-2d minutes, %-2d seconds)\n" \
       "$PROSYNC_TSN_GAP" "$PROSYNC_HOURS_TIME_GAP" "$PROSYNC_MINUTES_TIME_GAP" "$PROSYNC_SECONDS_TIME_GAP"
printf "\n"
printf "############################################################################################################\n"
printf " ProSync Meta Checking\n"
printf "############################################################################################################\n"
echo "  * SOURCE META"
echo "   - PROSYNC_SOURCE_MODE: ${PROSYNC_SOURCE_MODE}"
echo "   - PROSYNC_SOURCE_TOP_ID: ${PROSYNC_SOURCE_TOP_ID}"
echo "   - PROSYNC_SOURCE_DBLINK: ${PROSYNC_SOURCE_DBLINK}"
echo
echo "  * TARGET META"
echo "   - PROSYNC_TARGET_MODE: ${PROSYNC_TARGET_MODE}"
echo "   - PROSYNC_TARGET_TOP_ID: ${PROSYNC_TARGET_TOP_ID}"
echo "   - PROSYNC_TARGET_DBLINK: ${PROSYNC_TARGET_DBLINK}"
echo ""
echo ""
echo ""